name: docker-image

on:
  workflow_dispatch:
    inputs:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.9.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          file: ./at-buildimage/Dockerfile
          push: true
          tags: |
            atsigncompany/filebin2:automated
            atsigncompany/filebin2:latest
            atsigncompany/filebin2:GHA${{ github.run_number }}
          platforms: |
            linux/amd64